# Generated by Django 4.2.5 on 2024-04-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_handler', '0003_questions_stu'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='qs_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
