# Generated by Django 4.2.5 on 2023-12-21 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pycompiler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code',
            old_name='input',
            new_name='code',
        ),
    ]
