# Generated by Django 4.2.5 on 2023-12-30 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pycompiler', '0003_student_faculty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='rollmo',
            new_name='rollno',
        ),
    ]
