# Generated by Django 4.2.5 on 2024-03-12 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pycompiler', '0002_alter_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
