# Generated by Django 4.2.5 on 2024-04-17 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pycompiler', '0003_remove_student_user_delete_faculty_delete_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
