# Generated by Django 4.2.5 on 2024-04-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pycompiler', '0004_code_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='tc_pass',
            field=models.BooleanField(null=True),
        ),
    ]
