# Generated by Django 4.2.5 on 2024-04-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pycompiler', '0005_code_tc_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='qs_id',
            field=models.IntegerField(null=True),
        ),
    ]
